[project]
org-name = "cellery_hub_api"
version = "0.1.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "mysql-connector-java"
    version = "5.1.6"
    path = "./src/db/libs/mysql-connector-java-5.1.6.jar"
    groupId = "mysql"
    modules = ["core"]
