[security]
certfile="./security/api-tls.crt"
keyfile="./security/api-tls.pem"
truststore="./security/truststore.p12"
truststorepass="ballerina"

[idp.oidc]
clientid="celleryhubapplication"
clientsecret="celleryhubapplication"

[portal]
publicurl="https://hub.cellery.io:9000"

[database]
host="localhost"
port=3306
default="CELLERY_HUB"
user="root"
password="root"

[filter.captcha]
secret="someSecret"
endpoint="https://www.google.com/recaptcha/api/siteverify"
[filter.captcha.engaged]
paths="[{\"path\" : \"/api/0.1.0/orgs/*\", \"method\": \"post\"}]"
[filter.captcha.max.allowd.organization]
count=3

[idp]
endpoint="https://idp.hub.cellery.io:9443"
username="admin"
password="admin"
[idp.token]
endpoint="/oauth2/token"
[idp.introspection]
endpoint="/oauth2/introspect"
[idp.scim2.user]
endpoint="/scim2/Users"

[token.cache]
expiry=1800000
capacity=500

[b7a.log]
level="DEBUG"

[b7a.sql.connection.auto]
commit=true
[b7a.sql.max.pool]
size=100
